# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
var_box            = 'oel8'
var_vm_name        = 'docker'
var_mem_size       = 4048  # More would be better.
var_cpus           = 2 # 2 cores
var_non_rotational = 'on' # SSD
var_disk1_name      = 'D:\VMBOXES\docker\docker-u01.vdi'
var_disk1_size      = 100
var_disk2_name      = 'D:\VMBOXES\docker\docker-images.vdi'
var_disk2_size      = 150


Vagrant.configure("2") do |config|
  config.vm.box = var_box
  config.vm.network "public_network", ip: "192.168.0.21"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = var_mem_size
    vb.cpus   = var_cpus
    vb.name   = var_vm_name
    
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', var_non_rotational]

    unless File.exist?(var_disk1_name)
      vb.customize ['createhd', '--filename', var_disk1_name, '--size', var_disk1_size * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--nonrotational', var_non_rotational, '--medium', var_disk1_name]

    unless File.exist?(var_disk2_name)
      vb.customize ['createhd', '--filename', var_disk2_name, '--size', var_disk2_size * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--nonrotational', var_non_rotational, '--medium', var_disk2_name]
 end

  config.vm.provision "shell", inline: <<-SHELL
    sh /vagrant/scripts/setup.sh
  SHELL
end
