box: oel8
vm_name: ol8d21v01
mem_size: 10240
cpus: 2
public_ip: 192.168.1.21
disk1_name: D:\VMBOXES\ol8d21v01\ol8_21_u01.vdi
disk2_name: D:\VMBOXES\ol8d21v01\ol8_21_u02.vdi
non_rotational: 'on'
disk_size: 100
