box: oel7
vm_name: ol7_19_vagrant
mem_size: 4096
cpus: 4
public_ip: 192.168.1.24
disk1_name: D:\VMBOXES\ol7_19_vagrant\ol7_19_u01.vdi
disk2_name: D:\VMBOXES\ol7_19_vagrant\ol7_19_u02.vdi
non_rotational: 'on'
disk_size: 100
