box: generic/centos7
vm_name: testvm
public_ip: 192.168.3.31
esxi_hostport: 22
esxi_disk_store: VMSTORE
guest_name: testvm
guest_memsize: 2048
guest_numvcpus: 1
guest_guestos: 'centos-64'
esxi_virtual_network: VLAN20