box: oel7
vm_name: ol7122v01
mem_size: 4096
cpus: 4
public_ip: 192.168.1.26
vm_name: ol7122v01
disk1_name: D:\VMBOXES\ol7122v01\ol7_122_u01.vdi
disk2_name: D:\VMBOXES\ol7122v01\ol7_122_u02.vdi
non_rotational: 'on'
disk_size: 100
