Vagrant.configure("2") do |config|
    config.vm.box = "generic/oracle8"
    config.vm.hostname = "testvm"
    config.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = "192.168.1.12"
      esxi.esxi_username = "root"
      esxi.esxi_password = "Nithin#0712"
      esxi.esxi_hostport = "22"
      esxi.esxi_virtual_network = "PRODUCTION"
      esxi.esxi_disk_store = "VMSTORE"
      esxi.guest_name = "oel8-vm"
      esxi.guest_memsize = "2048"
      esxi.guest_numvcpus = "2"
      esxi.guest_disk_type = 'thin'
      esxi.guest_guestos = 'centos-64'
      esxi.guest_username = 'vagrant'
      esxi.guest_nic_type = 'vmxnet3'
    end
    config.vm.network "public_network", type: "static", ip: "192.168.1.20"
   # config.vm.provider :vmware_esxi do |esxi|
   #   esxi.customize ['createhd', '--filename', 'disk2.vmdk', '--size', 10240] # Adjust the size as needed
   #   esxi.customize ['storageattach', :id, '--storagectl', 'SCSIController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'disk2.vmdk']
   # end
  end
  